[keys]
prefix = "ctrl+space"
previous_tab = "prefix+h"
next_tab = "prefix+l"
new_tab = "prefix+n"
focus_pane_left = "prefix+left"
focus_pane_right = "prefix+right"

[ui.toast]
delivery = "off"

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_sort = "spaces"

[experimental]
pane_history = false

[ui.sound]
enabled = true
